"""add games table

Revision ID: 00c13598a6a8
Revises: bb35a306dd14
Create Date: 2026-08-20 01:26:10.262250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c13598a6a8'
down_revision: Union[str, Sequence[str], None] = 'bb35a306dd14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('game_type_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('start_time_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('venue', sa.String(length=100), nullable=True),
    sa.Column('venue_timezone', sa.String(length=50), nullable=True),
    sa.Column('neutral_site', sa.Boolean(), nullable=False),
    sa.Column('game_state', sa.String(length=10), nullable=True),
    sa.Column('game_schedule_state', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_away_team_id'), 'games', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_games_game_date'), 'games', ['game_date'], unique=False)
    op.create_index(op.f('ix_games_game_type_id'), 'games', ['game_type_id'], unique=False)
    op.create_index(op.f('ix_games_home_team_id'), 'games', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_games_season_id'), 'games', ['season_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_season_id'), table_name='games')
    op.drop_index(op.f('ix_games_home_team_id'), table_name='games')
    op.drop_index(op.f('ix_games_game_type_id'), table_name='games')
    op.drop_index(op.f('ix_games_game_date'), table_name='games')
    op.drop_index(op.f('ix_games_away_team_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
