"""add game_events table

Revision ID: 12d72a08e8ac
Revises: cade54cee30b
Create Date: 2026-08-22 19:08:31.590433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12d72a08e8ac'
down_revision: Union[str, Sequence[str], None] = 'cade54cee30b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=True),
    sa.Column('period_type', sa.String(length=10), nullable=True),
    sa.Column('time_in_period', sa.String(length=10), nullable=True),
    sa.Column('time_remaining', sa.String(length=10), nullable=True),
    sa.Column('situation_code', sa.String(length=10), nullable=True),
    sa.Column('home_team_defending_side', sa.String(length=10), nullable=True),
    sa.Column('type_code', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('event_owner_team_id', sa.Integer(), nullable=True),
    sa.Column('x_coord', sa.Float(), nullable=True),
    sa.Column('y_coord', sa.Float(), nullable=True),
    sa.Column('zone_code', sa.String(length=2), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['event_owner_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'event_id', name='uq_game_events_game_event')
    )
    op.create_index(op.f('ix_game_events_event_owner_team_id'), 'game_events', ['event_owner_team_id'], unique=False)
    op.create_index(op.f('ix_game_events_game_id'), 'game_events', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_events_game_id'), table_name='game_events')
    op.drop_index(op.f('ix_game_events_event_owner_team_id'), table_name='game_events')
    op.drop_table('game_events')
    # ### end Alembic commands ###
