"""remove player sweater number

Revision ID: 1eedd79dd288
Revises: 19b0e6b6847d
Create Date: 2026-08-18 01:44:56.974484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eedd79dd288'
down_revision: Union[str, Sequence[str], None] = '19b0e6b6847d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'sweater_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('sweater_number', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
