"""add shifts table

Revision ID: 44299e5a053e
Revises: 12d72a08e8ac
Create Date: 2026-08-23 14:24:18.855482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44299e5a053e'
down_revision: Union[str, Sequence[str], None] = '12d72a08e8ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('shift_number', sa.Integer(), nullable=True),
    sa.Column('start_time_seconds', sa.Integer(), nullable=False),
    sa.Column('end_time_seconds', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', 'period', 'start_time_seconds', name='uq_player_shift_game_player_period_start')
    )
    op.create_index(op.f('ix_shifts_game_id'), 'shifts', ['game_id'], unique=False)
    op.create_index(op.f('ix_shifts_player_id'), 'shifts', ['player_id'], unique=False)
    op.create_index(op.f('ix_shifts_team_id'), 'shifts', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shifts_team_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_player_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_game_id'), table_name='shifts')
    op.drop_table('shifts')
    # ### end Alembic commands ###
