"""add is_nhl column to teams table

Revision ID: 4d2616bf6f1b
Revises: 00c13598a6a8
Create Date: 2026-08-21 21:48:15.838050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d2616bf6f1b'
down_revision: Union[str, Sequence[str], None] = '00c13598a6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('is_nhl', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'is_nhl')
    # ### end Alembic commands ###
