"""create players table

Revision ID: 52e557ff9503
Revises: 6c1e871eed05
Create Date: 2026-08-18 01:10:55.124926

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "52e557ff9503"
down_revision: Union[str, Sequence[str], None] = "6c1e871eed05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("sweater_number", sa.Integer(), nullable=True),
        sa.Column("position_code", sa.String(length=1), nullable=True),
        sa.Column("shoots_catches", sa.String(length=1), nullable=True),
        sa.Column("height_in_inches", sa.Integer(), nullable=True),
        sa.Column("weight_in_pounds", sa.Integer(), nullable=True),
        sa.Column("height_in_centimeters", sa.Integer(), nullable=True),
        sa.Column("weight_in_kilograms", sa.Integer(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("birth_city", sa.String(length=100), nullable=True),
        sa.Column("birth_country", sa.String(length=3), nullable=True),
        sa.Column("birth_state_province", sa.String(length=100), nullable=True),
        sa.Column("headshot_url", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("players")
    # ### end Alembic commands ###
