"""update standings table

Revision ID: 6c1e871eed05
Revises: 707a999150ab
Create Date: 2026-08-14 01:08:38.999082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c1e871eed05'
down_revision: Union[str, Sequence[str], None] = '707a999150ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standings', sa.Column('clinch_indicator', sa.String(length=5), nullable=True))
    op.add_column('standings', sa.Column('home_points', sa.Integer(), nullable=True))
    op.add_column('standings', sa.Column('road_points', sa.Integer(), nullable=True))
    op.add_column('standings', sa.Column('home_games_played', sa.Integer(), nullable=True))
    op.add_column('standings', sa.Column('road_games_played', sa.Integer(), nullable=True))
    op.add_column('standings', sa.Column('home_goal_for', sa.Integer(), nullable=True))
    op.add_column('standings', sa.Column('home_goal_against', sa.Integer(), nullable=True))
    op.add_column('standings', sa.Column('road_goal_for', sa.Integer(), nullable=True))
    op.add_column('standings', sa.Column('road_goal_against', sa.Integer(), nullable=True))
    op.add_column('standings', sa.Column('home_regulation_wins', sa.Integer(), nullable=True))
    op.add_column('standings', sa.Column('road_regulation_wins', sa.Integer(), nullable=True))
    op.add_column('standings', sa.Column('home_regulation_plus_ot_wins', sa.Integer(), nullable=True))
    op.add_column('standings', sa.Column('road_regulation_plus_ot_wins', sa.Integer(), nullable=True))
    op.add_column('standings', sa.Column('l10_wins', sa.Integer(), nullable=True))
    op.add_column('standings', sa.Column('l10_losses', sa.Integer(), nullable=True))
    op.add_column('standings', sa.Column('l10_ot_losses', sa.Integer(), nullable=True))
    op.add_column('standings', sa.Column('l10_points', sa.Integer(), nullable=True))
    op.add_column('standings', sa.Column('l10_goal_for', sa.Integer(), nullable=True))
    op.add_column('standings', sa.Column('l10_goal_against', sa.Integer(), nullable=True))
    op.add_column('standings', sa.Column('l10_goal_differential', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standings', 'l10_goal_differential')
    op.drop_column('standings', 'l10_goal_against')
    op.drop_column('standings', 'l10_goal_for')
    op.drop_column('standings', 'l10_points')
    op.drop_column('standings', 'l10_ot_losses')
    op.drop_column('standings', 'l10_losses')
    op.drop_column('standings', 'l10_wins')
    op.drop_column('standings', 'road_regulation_plus_ot_wins')
    op.drop_column('standings', 'home_regulation_plus_ot_wins')
    op.drop_column('standings', 'road_regulation_wins')
    op.drop_column('standings', 'home_regulation_wins')
    op.drop_column('standings', 'road_goal_against')
    op.drop_column('standings', 'road_goal_for')
    op.drop_column('standings', 'home_goal_against')
    op.drop_column('standings', 'home_goal_for')
    op.drop_column('standings', 'road_games_played')
    op.drop_column('standings', 'home_games_played')
    op.drop_column('standings', 'road_points')
    op.drop_column('standings', 'home_points')
    op.drop_column('standings', 'clinch_indicator')
    # ### end Alembic commands ###
