"""create standings table

Revision ID: 707a999150ab
Revises: bc5f4632ebdc
Create Date: 2026-08-12 21:43:39.624352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '707a999150ab'
down_revision: Union[str, Sequence[str], None] = 'bc5f4632ebdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('conference_name', sa.String(length=50), nullable=True),
    sa.Column('conference_abbrev', sa.String(length=10), nullable=True),
    sa.Column('division_name', sa.String(length=50), nullable=True),
    sa.Column('division_abbrev', sa.String(length=10), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('ot_losses', sa.Integer(), nullable=True),
    sa.Column('ties', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('point_pctg', sa.Float(), nullable=True),
    sa.Column('goal_for', sa.Integer(), nullable=True),
    sa.Column('goal_against', sa.Integer(), nullable=True),
    sa.Column('goal_differential', sa.Integer(), nullable=True),
    sa.Column('home_wins', sa.Integer(), nullable=True),
    sa.Column('home_losses', sa.Integer(), nullable=True),
    sa.Column('home_ot_losses', sa.Integer(), nullable=True),
    sa.Column('road_wins', sa.Integer(), nullable=True),
    sa.Column('road_losses', sa.Integer(), nullable=True),
    sa.Column('road_ot_losses', sa.Integer(), nullable=True),
    sa.Column('regulation_wins', sa.Integer(), nullable=True),
    sa.Column('regulation_plus_ot_wins', sa.Integer(), nullable=True),
    sa.Column('shootout_wins', sa.Integer(), nullable=True),
    sa.Column('shootout_losses', sa.Integer(), nullable=True),
    sa.Column('streak_code', sa.String(length=5), nullable=True),
    sa.Column('streak_count', sa.Integer(), nullable=True),
    sa.Column('wildcard_sequence', sa.Integer(), nullable=True),
    sa.Column('league_sequence', sa.Integer(), nullable=True),
    sa.Column('conference_sequence', sa.Integer(), nullable=True),
    sa.Column('division_sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'season_id', name='uq_standing_team_season')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standings')
    # ### end Alembic commands ###
