"""create teams table

Revision ID: 9d62e75b8c44
Revises: 
Create Date: 2026-08-12 00:31:04.242849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d62e75b8c44'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbrev', sa.String(length=5), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('dark_logo', sa.String(length=255), nullable=True),
    sa.Column('first_season', sa.String(length=8), nullable=True),
    sa.Column('last_season', sa.String(length=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('conference', sa.String(length=50), nullable=True),
    sa.Column('division', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    # ### end Alembic commands ###
