"""remove skater and goalie stats tables

Revision ID: bb35a306dd14
Revises: 1eedd79dd288
Create Date: 2026-08-19 00:25:47.997813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb35a306dd14'
down_revision: Union[str, Sequence[str], None] = '1eedd79dd288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goalie_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('game_type_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_started', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('ties', sa.Integer(), nullable=True),
    sa.Column('ot_losses', sa.Integer(), nullable=True),
    sa.Column('shots_against', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('goals_against_avg', sa.Float(), nullable=True),
    sa.Column('save_pctg', sa.Float(), nullable=True),
    sa.Column('shutouts', sa.Integer(), nullable=True),
    sa.Column('time_on_ice_seconds', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('pim', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'team_id', 'season_id', 'game_type_id', name='uq_goalie_stats_player_team_season_game_type')
    )
    op.create_index(op.f('ix_goalie_stats_player_id'), 'goalie_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_goalie_stats_season_id'), 'goalie_stats', ['season_id'], unique=False)
    op.create_index(op.f('ix_goalie_stats_team_id'), 'goalie_stats', ['team_id'], unique=False)
    op.create_table('skater_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('game_type_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.Column('pim', sa.Integer(), nullable=True),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('shooting_pctg', sa.Float(), nullable=True),
    sa.Column('avg_toi_seconds', sa.Integer(), nullable=True),
    sa.Column('faceoff_winning_pctg', sa.Float(), nullable=True),
    sa.Column('power_play_goals', sa.Integer(), nullable=True),
    sa.Column('power_play_points', sa.Integer(), nullable=True),
    sa.Column('shorthanded_goals', sa.Integer(), nullable=True),
    sa.Column('shorthanded_points', sa.Integer(), nullable=True),
    sa.Column('game_winning_goals', sa.Integer(), nullable=True),
    sa.Column('ot_goals', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'team_id', 'season_id', 'game_type_id', name='uq_skater_stats_player_team_season_game_type')
    )
    op.create_index(op.f('ix_skater_stats_player_id'), 'skater_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_skater_stats_season_id'), 'skater_stats', ['season_id'], unique=False)
    op.create_index(op.f('ix_skater_stats_team_id'), 'skater_stats', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skater_stats_team_id'), table_name='skater_stats')
    op.drop_index(op.f('ix_skater_stats_season_id'), table_name='skater_stats')
    op.drop_index(op.f('ix_skater_stats_player_id'), table_name='skater_stats')
    op.drop_table('skater_stats')
    op.drop_index(op.f('ix_goalie_stats_team_id'), table_name='goalie_stats')
    op.drop_index(op.f('ix_goalie_stats_season_id'), table_name='goalie_stats')
    op.drop_index(op.f('ix_goalie_stats_player_id'), table_name='goalie_stats')
    op.drop_table('goalie_stats')
    # ### end Alembic commands ###
