"""create seasons table

Revision ID: bc5f4632ebdc
Revises: f682bffe5c06
Create Date: 2026-08-12 21:33:04.550896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5f4632ebdc'
down_revision: Union[str, Sequence[str], None] = 'f682bffe5c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conferences_in_use', sa.Boolean(), nullable=True),
    sa.Column('divisions_in_use', sa.Boolean(), nullable=True),
    sa.Column('point_for_ot_loss_in_use', sa.Boolean(), nullable=True),
    sa.Column('regulation_wins_in_use', sa.Boolean(), nullable=True),
    sa.Column('row_in_use', sa.Boolean(), nullable=True),
    sa.Column('standings_end', sa.Date(), nullable=False),
    sa.Column('standings_start', sa.Date(), nullable=False),
    sa.Column('ties_in_use', sa.Boolean(), nullable=True),
    sa.Column('wildcard_in_use', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seasons')
    # ### end Alembic commands ###
