"""make is_nhl not nullable

Revision ID: e7f682040fd6
Revises: 4d2616bf6f1b
Create Date: 2026-08-21 21:52:58.656488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f682040fd6'
down_revision: Union[str, Sequence[str], None] = '4d2616bf6f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'is_nhl',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'is_nhl',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
