"""update shifts table

Revision ID: ece52a6fcdc3
Revises: 44299e5a053e
Create Date: 2026-08-23 16:32:35.196705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece52a6fcdc3'
down_revision: Union[str, Sequence[str], None] = '44299e5a053e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_player_shift_game_player_period_start'), 'shifts', type_='unique')
    op.create_index('ix_shifts_game_period_start_end', 'shifts', ['game_id', 'period', 'start_time_seconds', 'end_time_seconds'], unique=False)
    op.create_index('ix_shifts_player_game', 'shifts', ['player_id', 'game_id'], unique=False)
    op.create_unique_constraint('uq_shift_game_player_period_start_end', 'shifts', ['game_id', 'player_id', 'period', 'start_time_seconds', 'end_time_seconds'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_shift_game_player_period_start_end', 'shifts', type_='unique')
    op.drop_index('ix_shifts_player_game', table_name='shifts')
    op.drop_index('ix_shifts_game_period_start_end', table_name='shifts')
    op.create_unique_constraint(op.f('uq_player_shift_game_player_period_start'), 'shifts', ['game_id', 'player_id', 'period', 'start_time_seconds'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
