"""remove conference and division column from teams

Revision ID: f682bffe5c06
Revises: 9d62e75b8c44
Create Date: 2026-08-12 21:02:19.579910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f682bffe5c06'
down_revision: Union[str, Sequence[str], None] = '9d62e75b8c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'conference')
    op.drop_column('teams', 'division')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('division', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('conference', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
